# Firebase
FIREBASE_PROJECT = 'YOUR_FIREBASE_PROJECT_URL'
FIREBASE_SECRET = 'YOUR_FIREBASE_SECRET'
AUTH_PAYLOAD = {"uid": "1", "auth_data": "foo", "other_auth_data": "bar"}
# For example {"uid": "1", "auth_data": "foo", "other_auth_data": "bar"}
ROOT_OBJECT = 'sms'

# Twilio
ACCOUNT_SID = "YOUR_TWILIO_ACCOUNT_SID"
AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN"
MY_PHONE_NUMBER = 'YOUR_TWILIO_PHONE_NUMBER' # Example : +33611223344

# Twitter
# CONSUMER_KEY        = 'YOUR_CONSUMER_KEY'
# CONSUMER_SECRET     = 'YOUR_CONSUMER_SECRET'
# ACCESS_TOKEN        = 'YOUR_ACCESS_TOKEN'
# ACCESS_TOKEN_SECRET = 'YOUR_ACCESS_TOKEN_SECRET'

# MATCH_HASHTAG = 'YOUR_HASHTAG'
